import {
  GET_USER_API,
  POST_USER_API,
  POST_USER_LOGIN_API,
  GET_USER_CHECK_API,
  GET_IPAPI_API
} from "./apiEndpoints";

export { GET_USER_API, POST_USER_API, POST_USER_LOGIN_API,GET_USER_CHECK_API, GET_IPAPI_API };
